<!DOCTYPE html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <title>Article List</title>
    </head>
    <body>
        <div class="container">
            <h2>Article list</h2>
            <table>
                <tr>
                    <th>Title</th>
                    <th>Description</th>
                    <th>Body</th>
                    <th>Article view</th>
                    <th>Edit article</th>
                    <th>User Id</th>
                    <th>Category Id</th>
                </tr>
                <?php foreach($articles as $article): ?>
                <tr>
                        <td><?=$article['title']?></td>
                        <td><?=$article['description']?></td>
                        <td><?=$article['body']?></td>
                        <td><a href="index.php?route=articleView&title=<?= $article['title'] ?>
                                    &description=<?= $article['description'] ?>
                                    &body=<?= $article['body'] ?>
                                    &category=<?= $article['categoryId'] ?>">
                                Article View
                            </a></td>
                        <td><a href="index.php?route=updateArticleForm&title=<?= $article['title'] ?>
                                    &description=<?= $article['description'] ?>
                                    &body=<?= $article['body'] ?>
                                    &category=<?= $article['categoryId'] ?>">
                                Edit article
                            </a>
                        </td>
                        <td><?= $article['userId']; ?></td>
                        <td><?= $article['categoryId']; ?></td>
                    </tr>
                <?php endforeach; ?>
            </table>
               <form class="" action="index.php?route=articleList" method="">
                    <input type="hidden" name="route" value="articleList">
                    <input type="text" name="articleFilter" value="">
                    <input type="submit" name="" value="search">
               </form>
          </div>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>    
     </body>
</html>

