<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <title>Article Form</title>
	</head>
	<body>
	<div class="container-fluid bg-light py-3">
    <div class="row">
        <div class="col-md-6 mx-auto">
        <div class="card card-body">
        <h3 class="text-center mb-4">Article Form</h3>
            <form action="index.php?route=saveArticle" enctype="multipart/form-data" method="POST">
                <div class="form-group">
			        Title: <input class="form-control input-lg" type="text" name="title" value="<?php if(isset($params->title)){echo $params->title;}?>" />
			    </div>
                <div class="form-group">
			        Description: <textarea class="form-control" rows="2" name="description" value="<?php if(isset($article->title)){echo $article->description;}?>"></textarea>
			    </div>
                <div class="form-group">
                    Body: <textarea class="form-control" rows="5" name="body" value="<?php if(isset($article->title)){echo $article->body;}?>"></textarea>
			    </div>
                <div class="form-group">
                    Image: <div class="custom-file">
                    <input name ="image" type="file" class="custom-file-input">
                    <label class="custom-file-label" for="exampleInputFile">Select image...</label>
                </div>
                <div class="form-group">
                    <select name="categoryId" placeholder="Category" type="text" class="form-control">
                        <?php foreach ($categories as $category) : ?>
                            <option value="<?=$category['name']?>"><?=$category['name']?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div class="form-group">
                    User: <input class="form-control input-lg" type="text" name="userId" value="<?php if(isset($article->title)){echo $article->userId;}?>" />
                </div>
		        <input type="submit">    
            </form>
        </div>
        </div>
    </div>
    </div>
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>    
	</body>
</html>