<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <h3 class="text-center">Article Update</h3>
            <form action="index.php?route=saveArticle" method="POST">
                <div class="form-group">
                    <input name="title" value="<?= $_GET['title'] ?>" type="text"
                           class="form-control">
                </div>
                <div class="form-group">
                    <textarea name="description" class="form-control"><?= $_GET['description'] ?></textarea>
                </div>
                <div class="form-group">
                    <textarea name="body" placeholder="Body" class="form-control"> <?= $_GET['body'] ?></textarea>
                </div>
                <div class="form-group">
                    Image: <div class="custom-file">
                    <input name ="image" type="file" class="custom-file-input">
                    <label class="custom-file-label" for="exampleInputFile">Select image...</label>
                </div>
                <div class="form-group">
                    <input name="username" value="<?php if(isset($article->title)){echo $article->username;}?>" placeholder="Username" type="text" class="form-control">
                </div>
                <div class="form-group">
                    <select name="categoryId" type="text" class="form-control">
                        <?php foreach ($categories as $category) : ?>
                            <option value="<?php echo $category['name']; ?>"><?php echo $category['name']; ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <input type="submit" class="btn btn-block btn-primary" name="submit-article" id="submit-article">
            </form>
        </div>
    </div>
</div>