<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <title>Category Form</title>
    </head>
	<body>
	<div class="container-fluid bg-light py-3">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <div class="card card-body">
				<h3 class="text-center mb-4">Category Form</h3>
                <form action="index.php?route=createCategory" method="POST">
                    <div class="form-group">
                        <input type="text" name="categoryName" value="<?php if(isset($category['name'])){echo $category['name'];}?>" class="form-control">
                    </div>
                 <input type="submit" class="btn btn-block btn-primary" name="submitCategory" id="submitCategory">
                </form>
            </div>  
        </div>  
    </div>
    </div>               
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>    
	</body>
</html>