<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
	</head>
	<body>
	
		<ul>
			<?php if (!isLoggedIn()): ?>
			<li><a href="index.php?route=loginForm">Login</a></li>
			<?php else: ?>
			<li><a href="index.php?route=createUserForm">Create User</a></li>
			<li><a href="index.php?route=userList">List Users</a></li>
			<li><a href="index.php?route=createArticleForm">Create Article</a></li>
			<li><a href="index.php?route=articleList">List Articles</a></li>
			<li><a href="index.php?route=createCategoryForm">Create Category</a></li>
			<?php endif; ?>
		</ul> 
		<?php if (strlen($message) > 0):?>
		<div>
			<?php $message ?>
		</div>
		<?php endif; ?>
		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>    
	</body>
</html>