<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
    	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <title>Register User</title>
	</head>
	<body>
	<div class="container">
        <div class="row align-items-center justify-content-center">
            <div class="col-sm-6">
				<form class="" id="createUser" action="index.php?route=<?php if(isset($user->email)): echo 'userUpdate'; else: echo 'createUser'; endif;?>" method="post" enctype="multipart/form-data">
                    <h5>User Update Form</h5>
                    <div class="form-group">
                        <input type="email" value="<?php if(isset($user->email)){echo $user->email;}?>" name="email" class="form-control" aria-describedby="emailHelp" placeholder="Email">
                    </div>
                    <div class="form-group">
                    <input type="password" name="password" value="<?php if(isset($user->email)){echo $user->password;}?>" class="form-control" placeholder="Password">
                    </div>
                    <div class="form-group">
                        <input type="password" name="password-2" value="<?php if(isset($user->email)){echo $user->password-2;}?>"class="form-control" placeholder="Confirm password">
                    </div>
                    <div class="form-group">
                        <input type="text" name="firstName" value="<?php if(isset($user->email)){echo $user->firstName;}?>" class="form-control" placeholder="First name">
                    </div>
                    <div class="form-group">
                        <input type="text" name="lastName" value="<?php if(isset($user->email)){echo $user->lastName;}?>" class="form-control" placeholder="Last name">
                    </div>
                    <div class="form-group">
                        <input type="text" name="username" value="<?php if(isset($user->email)){echo $user->username;}?>" class="form-control" placeholder="Username">
                    </div>
                    <div class="form-group">
                        <label for="image">Image</label>
                        <input type="file" name="image" class="form-control">
                    </div>
                    <div class="form-group">
                        <select class="" name="status">
                            <option value="1">Active</option>
                            <option value="0">Inactive</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <input type="text" name="age" value="" class="form-control" placeholder="Age">
                    </div>
                    <button type="submit" class="btn btn-primary" style="width: 100%;">Create User</button>
				</form>
			</div>
        </div>
    </div>
		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>    
	</body>
</html>