<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <h1><?= isset($_GET['email']) ? 'updateUser' : 'createUser' ?></h1>
            <form method="post" action="index.php?route=<?= isset($_GET['email']) ? 'updateUser' : 'createUser' ?>">
                <div class="form-group">
                    <input class="form-control" name="email" type="email" placeholder="E-mail"
                           value="<?= isset($_GET['email']) ? $_GET['email'] : '' ?>">
                </div>
                <div class="form-group">
                    <input class="form-control" name="password" type="password" placeholder="Password">
                </div>
                <div class="form-group">
                    <input class="form-control" name="password-2" type="password" placeholder="Confirm password">
                </div>
                <input type="hidden" name="old_email" value="<?= isset($_GET['email']) ? $_GET['email'] : '' ?>">
                <input class="btn btn-primary btn-block" type="submit"
                       value="<?= isset($_GET['email']) ? 'updateUser' : 'createUser' ?>" id="submit">
            </form>
        </div>
    </div>
</div>
