<!DOCTYPE html>
<html>
	<head>
	</head>
	<body>
	
		<ul>
			<?php if (!isLoggedIn()): ?>
			<li><a href="index.php?route=login">Login</a></li>
			<?php else: ?>
			<li><a href="index.php?route=createUserForm">Create</a></li>
			<li><a href="index.php?route=userList">List Users</a></li>
			<?php endif; ?>
		</ul> 
		<?php if (strlen($message) > 0):?>
		<div>
			<?php=$message ?>
		</div>
		<?php endif; ?>
	</body>
</html>