<!DOCTYPE html>
<html>
	<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Register Form</title>

    <!-- Bootstrap -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
	</head>
	<body>
	<div class="container-fluid bg-light py-3">
    <div class="row">
        <div class="col-md-6 mx-auto">
                <div class="card card-body">
					<h3 class="text-center mb-4">Register Form</h3>
					<fieldset action="index.php?route=createUser" enctype="multipart/form-data" method="post">
						<div class="form-group">
							First name: <input class="form-control input-lg" type="text" name="firstName" value="" placeholder="Enter first name">
						</div>
						<div class="form-group">
							Last name: <input class="form-control input-lg" input type="text" name="lastName" value="" placeholder="Enter last name">
						</div>

						
			Username: <input type="text" name="username" value="" placeholder=" Enter username" />
			<br><br>
			Image: <input type="file" name="image" value="" />
			<br><br>
			Status: <input type="text" name="status" value="" placeholder="Enter your status" />
			<br><br>
			E-mail: <input type="text" name="email" value="" placeholder="Enter E-mail" />
			<br><br>
			Password: <input type="password" name="password" value="" placeholder="Enter password" />
			<br><br>
			Password: <input type="password" name="password-2" value="" placeholder="Retype password" />
			<br><br>
			<input type="submit">
		</form>

	</body>
</html>